[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true

[rpc_endpoints]
sepolia = "${URL_ETH_SEPOLIA}"
